name: tst
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types: [created, edited]
      

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger info
        run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action || 'N/A' }}"
          echo "PR #${{ github.event.pull_request.number || github.event.issue.number }}"
