name: sleepWorkflow

on:
  workflow_dispatch:

jobs:
  job1:
    needs: job4
    runs-on: ubuntu-latest
    steps:
      - name: Print message from job 1
        run: |
          echo "Hello from Job 1"
          # sleep 3

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from job 2
        run: |
          echo "Hello from Job 2"
          sleep 5

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from job 3
        run: |
          echo "Hello from Job 3"
          sleep 6

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from job 4
        run: |
          echo "Hello from Job 4"
          sleep 7
